#!/bin/sh
/usr/bin/aegis-exec -s -u user /usr/bin/gconftool -s --type=bool /apps/ControlPanel/Helium/Display/show-device-icons false
/usr/bin/aegis-exec -s -u user /usr/bin/gconftool -s --type=bool /apps/ControlPanel/Helium/Display/show-media-art false

exit 0
