#############################################################################
# Makefile for building: Helium
# Generated by qmake (2.01a) (Qt 4.7.4) on: So. Feb 26 21:54:27 2012
# Project:  Helium.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Helium.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gupnp-1.0 -I/usr/include/gssdp-1.0 -I/usr/include/libxml2 -I/usr/include/libsoup-2.4 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gupnp-av-1.0 -I/usr/include/gupnp-1.0 -I/usr/include/gssdp-1.0 -I/usr/include/libxml2 -I/usr/include/libsoup-2.4 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gupnp-1.0 -I/usr/include/gssdp-1.0 -I/usr/include/libxml2 -I/usr/include/libsoup-2.4 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gupnp-av-1.0 -I/usr/include/gupnp-1.0 -I/usr/include/gssdp-1.0 -I/usr/include/libxml2 -I/usr/include/libsoup-2.4 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -I/opt/gnome2/include/QtSystemInfo -Iqmlapplicationviewer -I/opt/gnome2/include -I/opt/gnome2/include/QtMobility -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/opt/gnome2/lib64
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -pthread -lgupnp-av-1.0 -lgupnp-1.0 -lgssdp-1.0 -lxml2 -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0 -L/opt/gnome2/lib64 -lQtSystemInfo -lQtDeclarative -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		upnp/upnprenderer.cpp \
		upnp/upnpmediaserver.cpp \
		upnp/upnpdevice.cpp \
		upnp/upnpdevicemodel.cpp \
		upnp/upnpservermodel.cpp \
		upnp/upnprenderermodel.cpp \
		upnp/browsemodel.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc_qmlapplicationviewer.cpp \
		moc_upnprenderer.cpp \
		moc_upnpmediaserver.cpp \
		moc_upnpdevice.cpp \
		moc_upnpdevicemodel.cpp \
		moc_upnpservermodel.cpp \
		moc_upnprenderermodel.cpp \
		moc_browsemodel.cpp
OBJECTS       = main.o \
		upnprenderer.o \
		upnpmediaserver.o \
		upnpdevice.o \
		upnpdevicemodel.o \
		upnpservermodel.o \
		upnprenderermodel.o \
		browsemodel.o \
		qmlapplicationviewer.o \
		moc_qmlapplicationviewer.o \
		moc_upnprenderer.o \
		moc_upnpmediaserver.o \
		moc_upnpdevice.o \
		moc_upnpdevicemodel.o \
		moc_upnpservermodel.o \
		moc_upnprenderermodel.o \
		moc_browsemodel.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/mobility.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Helium.pro
QMAKE_TARGET  = Helium
DESTDIR       = 
TARGET        = Helium

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Helium.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/mobility.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtDeclarative.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Helium.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/mobility.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtDeclarative.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Helium.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Helium1.0.0 || $(MKDIR) .tmp/Helium1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Helium1.0.0/ && $(COPY_FILE) --parents qmlapplicationviewer/qmlapplicationviewer.h upnp/upnprenderer.h upnp/upnpmediaserver.h upnp/upnpdevice.h upnp/upnpdevicemodel.h upnp/upnpservermodel.h upnp/upnprenderermodel.h upnp/browsemodel.h .tmp/Helium1.0.0/ && $(COPY_FILE) --parents main.cpp upnp/upnprenderer.cpp upnp/upnpmediaserver.cpp upnp/upnpdevice.cpp upnp/upnpdevicemodel.cpp upnp/upnpservermodel.cpp upnp/upnprenderermodel.cpp upnp/browsemodel.cpp qmlapplicationviewer/qmlapplicationviewer.cpp .tmp/Helium1.0.0/ && (cd `dirname .tmp/Helium1.0.0` && $(TAR) Helium1.0.0.tar Helium1.0.0 && $(COMPRESS) Helium1.0.0.tar) && $(MOVE) `dirname .tmp/Helium1.0.0`/Helium1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Helium1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qmlapplicationviewer.cpp moc_upnprenderer.cpp moc_upnpmediaserver.cpp moc_upnpdevice.cpp moc_upnpdevicemodel.cpp moc_upnpservermodel.cpp moc_upnprenderermodel.cpp moc_browsemodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qmlapplicationviewer.cpp moc_upnprenderer.cpp moc_upnpmediaserver.cpp moc_upnpdevice.cpp moc_upnpdevicemodel.cpp moc_upnpservermodel.cpp moc_upnprenderermodel.cpp moc_browsemodel.cpp
moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qmlapplicationviewer/qmlapplicationviewer.h -o moc_qmlapplicationviewer.cpp

moc_upnprenderer.cpp: upnp/upnpdevice.h \
		upnp/refptrg.h \
		upnp/upnprenderer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) upnp/upnprenderer.h -o moc_upnprenderer.cpp

moc_upnpmediaserver.cpp: upnp/upnpdevice.h \
		upnp/refptrg.h \
		upnp/upnpmediaserver.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) upnp/upnpmediaserver.h -o moc_upnpmediaserver.cpp

moc_upnpdevice.cpp: upnp/refptrg.h \
		upnp/upnpdevice.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) upnp/upnpdevice.h -o moc_upnpdevice.cpp

moc_upnpdevicemodel.cpp: upnp/upnpdevice.h \
		upnp/refptrg.h \
		upnp/upnpdevicemodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) upnp/upnpdevicemodel.h -o moc_upnpdevicemodel.cpp

moc_upnpservermodel.cpp: upnp/upnpmediaserver.h \
		upnp/upnpdevice.h \
		upnp/refptrg.h \
		upnp/upnpservermodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) upnp/upnpservermodel.h -o moc_upnpservermodel.cpp

moc_upnprenderermodel.cpp: upnp/upnprenderer.h \
		upnp/upnpdevice.h \
		upnp/refptrg.h \
		upnp/upnpdevicemodel.h \
		upnp/upnprenderermodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) upnp/upnprenderermodel.h -o moc_upnprenderermodel.cpp

moc_browsemodel.cpp: upnp/refptrg.h \
		upnp/browsemodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) upnp/browsemodel.h -o moc_browsemodel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp upnp/upnprenderer.h \
		upnp/upnpdevice.h \
		upnp/refptrg.h \
		upnp/upnpdevicemodel.h \
		upnp/upnpmediaserver.h \
		upnp/upnpservermodel.h \
		upnp/upnprenderermodel.h \
		upnp/browsemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

upnprenderer.o: upnp/upnprenderer.cpp upnp/upnprenderer.h \
		upnp/upnpdevice.h \
		upnp/refptrg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o upnprenderer.o upnp/upnprenderer.cpp

upnpmediaserver.o: upnp/upnpmediaserver.cpp upnp/upnpmediaserver.h \
		upnp/upnpdevice.h \
		upnp/refptrg.h \
		upnp/browsemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o upnpmediaserver.o upnp/upnpmediaserver.cpp

upnpdevice.o: upnp/upnpdevice.cpp upnp/upnpdevice.h \
		upnp/refptrg.h \
		upnp/upnpmediaserver.h \
		upnp/upnprenderer.h \
		upnp/upnpdevicemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o upnpdevice.o upnp/upnpdevice.cpp

upnpdevicemodel.o: upnp/upnpdevicemodel.cpp upnp/refptrg.h \
		upnp/upnpdevicemodel.h \
		upnp/upnpdevice.h \
		upnp/upnprenderer.h \
		upnp/upnpmediaserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o upnpdevicemodel.o upnp/upnpdevicemodel.cpp

upnpservermodel.o: upnp/upnpservermodel.cpp upnp/upnpservermodel.h \
		upnp/upnpmediaserver.h \
		upnp/upnpdevice.h \
		upnp/refptrg.h \
		upnp/upnpdevicemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o upnpservermodel.o upnp/upnpservermodel.cpp

upnprenderermodel.o: upnp/upnprenderermodel.cpp upnp/upnprenderermodel.h \
		upnp/upnprenderer.h \
		upnp/upnpdevice.h \
		upnp/refptrg.h \
		upnp/upnpdevicemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o upnprenderermodel.o upnp/upnprenderermodel.cpp

browsemodel.o: upnp/browsemodel.cpp upnp/browsemodel.h \
		upnp/refptrg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o browsemodel.o upnp/browsemodel.cpp

qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

moc_qmlapplicationviewer.o: moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlapplicationviewer.o moc_qmlapplicationviewer.cpp

moc_upnprenderer.o: moc_upnprenderer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_upnprenderer.o moc_upnprenderer.cpp

moc_upnpmediaserver.o: moc_upnpmediaserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_upnpmediaserver.o moc_upnpmediaserver.cpp

moc_upnpdevice.o: moc_upnpdevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_upnpdevice.o moc_upnpdevice.cpp

moc_upnpdevicemodel.o: moc_upnpdevicemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_upnpdevicemodel.o moc_upnpdevicemodel.cpp

moc_upnpservermodel.o: moc_upnpservermodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_upnpservermodel.o moc_upnpservermodel.cpp

moc_upnprenderermodel.o: moc_upnprenderermodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_upnprenderermodel.o moc_upnprenderermodel.cpp

moc_browsemodel.o: moc_browsemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_browsemodel.o moc_browsemodel.cpp

####### Install

install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/Helium/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/Helium/qml/ 
	-$(INSTALL_DIR) /home/jens/Projects/Helium/qml/Helium $(INSTALL_ROOT)/opt/Helium/qml/


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/Helium/qml/Helium
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Helium/qml/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/Helium/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/Helium/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/Helium/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/opt/Helium/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/Helium/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Helium/bin/ 


install:  install_itemfolder_01 install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_target   FORCE

FORCE:

